### DISCUSSION TITLE
Github Contribution Influence

### DISCUSSION THREAD

**Discussion by daorren** [osmoscraft/osmosfeed#53] [Q&A] [answered]
I like this github-as-rss-reader idea very much, thank you for your efforts.

However, after a few days of using, I found that osmofeed influenced my github contribution.

I tried to set user_name & user_email in update-feed.yaml as below, but it didn't work.
```yaml
      - name: Deploy to GitHub Pages        
        uses: peaceiris/actions-gh-pages@v3        
        with:         
             github_token: ${{ secrets.GITHUB_TOKEN }}          
             publish_dir: ./public          
             user_name: 'github-actions[bot]'         
             user_email: 'github-actions[bot]@users.noreply.github.com'
```

So my question is, is there any way to keep my github contribution clean?

---

Edit:

It works
